// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.856
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"strings"

	"chatter/app/types"
)

func isUserAuthenticated(user types.User) bool {
	email := user.Email
	parts := strings.Split(email, "@")
	if len(parts) < 2 {
		return false
	}
	tail := parts[1]
	tail_parts := strings.Split(tail, ".")
	if len(tail_parts) < 1 {
		return false
	}
	domain := tail_parts[0]
	if domain == "anon" {
		return false
	}
	return true
}

func isUserCtxAuthenticated(ctx context.Context) bool {
	user_ctx := ctx.Value("user")
	if user_ctx == nil {
		return false
	}
	user := user_ctx.(types.User)
	return isUserAuthenticated(user)
}

func LoginAsAnon() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = Head("Chatter - Login").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Navbar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"section\"><div class=\"container\"><div class=\"card\"><header class=\"card-header\"><p class=\"card-header-title mx-auto is-size-3\" style=\"max-width:fit-content\">Você não está logado</p></header><footer class=\"card-footer\"><a href=\"/login\" class=\"card-footer-item\">Login </a> <a class=\"card-footer-item\" hx-get=\"/loginanon\" hx-trigger=\"click\">Fazer Login como Usuário Anônimo </a> <a href=\"/chatrooms\" class=\"card-footer-item\">Voltar </a></footer></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func LoginPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = Head("Chatter - Login").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Navbar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<section class=\"section\"><div class=\"container\"><div class=\"field\"><p class=\"control has-icons-left has-icons-right\"><input id=\"loginInput\" name=\"Email\" class=\"input\" type=\"email\" placeholder=\"Email\"> <span class=\"icon is-small is-left\"><i class=\"fas fa-envelope\"></i></span></p></div><div class=\"field\"><p class=\"control has-icons-left\"><input id=\"loginInput\" name=\"Password\" class=\"input\" type=\"password\" placeholder=\"Password\"> <span class=\"icon is-small is-left\"><i class=\"fas fa-lock\"></i></span></p></div><div class=\"field\"><p class=\"control\"><button class=\"button is-success\" hx-post=\"/login\" hx-include=\"#loginInput\">Login</button></p></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func RegisterPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = Head("Chatter - Register").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Navbar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<section class=\"section\"><div class=\"container\"><div class=\"field\"><div class=\"control has-icons-left has-icons-right\"><input id=\"registerInput\" name=\"Name\" class=\"input\" type=\"text\" placeholder=\"Username\"> <span class=\"icon is-small is-left\"><i class=\"fas fa-user\"></i></span></div><p class=\"control has-icons-left has-icons-right\"><input id=\"registerInput\" name=\"Email\" class=\"input\" type=\"email\" placeholder=\"Email\"> <span class=\"icon is-small is-left\"><i class=\"fas fa-envelope\"></i></span></p><p class=\"control has-icons-left\"><input id=\"registerInput\" name=\"Password\" class=\"input\" type=\"password\" placeholder=\"Password\"> <span class=\"icon is-small is-left\"><i class=\"fas fa-lock\"></i></span></p><p class=\"control has-icons-left\"><input id=\"registerInput\" name=\"RepeatPassword\" class=\"input\" type=\"password\" placeholder=\"Repeat Password\"> <span class=\"icon is-small is-left\"><i class=\"fas fa-lock\"></i></span></p></div><div class=\"field\"><p class=\"control\"><button class=\"button is-success\" hx-post=\"/register\" hx-include=\"#registerInput\">Register</button></p></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
